# Generated by Django 5.2.1 on 2025-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/'),
        ),
    ]
